### ISSUE TITLE
AttributeError: 'ReadDepth' object has no attribute '_transformed_or_normalized_'

### ISSUE THREAD

**Issue by juliandwillett** [ygidtu/trackplot#82]
I keep on getting this error when trying to run bigwig files. Any tips?

**Comment by ygidtu** [comment]
Hi,
   There is a left-out attributes in ReadDepth, I manage to fix it and release v0.2.6, please try to reinstall with `pip install -i https://pypi.org/simple/ trackplot`, or clone our repo to run with `main.py`, others pypi mirror or conda env will avilable later.
Best wishes
Yiming

**Comment by juliandwillett** [comment]
Thanks! That fixed it. For others, I used the following command to install the updated version:

`pip install trackplot==0.2.6`
