### ISSUE TITLE
By increasing the event length

### ISSUE THREAD

**Issue by sivasubramanics** [ygidtu/trackplot#93]
Hello Team,
Thanks for the great tool. 
I was trying to plot a region of 1 MB and the code crashes showing "KeyError: 'exon_id'", that doesn't make any sense. Because just by reducing the event length the plot completes with no issues.

Do we have maximum limit for event length?

CMD works: trackplot -e Dovetail_reconstructed_14OCT2019_v4_lg_2:51486277-51490011:+ -r pangenome.gtf --density density.list --output LK057.pdf -d 600
CMD didn't work: trackplot -e Dovetail_reconstructed_14OCT2019_v4_lg_2:50486277-51490011:+ -r pangenome.gtf --density density.list --output LK057.pdf -d 600

-
Siva

**Comment by ygidtu** [comment]
Hi,
   It seems like this error caused by your gtf file missing some of exon_id tags.
   Could you please give me more information like which version of trackplot do you use, and an exmaple of your gtf file for us to debugging?

Yours
Best

**Comment by sivasubramanics** [comment]
It was due to the absent tag "exon_id" in the GTF file. I converted gff2gtf using [agat](https://agat.readthedocs.io/en/latest/gff_to_gtf.html#agat) tools, and the output GTF is of GTF3.0 format, which by default does not come with "exon_id" tag. I had to edit the GTF file, then it worked. 

Probably we mention in the help that the GTF annotation should be of specific version?

**Comment by ygidtu** [comment]
Hi Siva,
  Thanks for your feedback, I'll check the GTF format generated by agat, and try to fix this in next release.
Yours,
Best
