### ISSUE TITLE
Set y-axis scale for different sample types

### ISSUE THREAD

**Issue by czfoo** [ygidtu/trackplot#97]
I'd like to plot bw files from my ATAC-Seq samples with the same y-axis scale for all samples alongside sashimi plots for my RNA-Seq samples with variable y-axis scales. Would that be possible, or has it not been worked into the current version?

**Comment by ygidtu** [comment]
Hi there, 
   I'm sorry for the late response, the same y-axis currently only worked globally, cannot set by groups. I'll try to work on that in late versions.
Best

**Comment by ygidtu** [comment]
Hi, 
  I update a new release v0.5.0, add --same-y-by-groups, please try with the latest version.
